/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.songmanagement;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LAPTOPVTC.VN
 */
public class EditArtistFrame extends javax.swing.JFrame {

    private ArrayList<Artist> artists;
    private ArrayList<Album> albums;
    private ArrayList<Song> list;
    private Artist artist;

    public EditArtistFrame(ArrayList<Song> list, int index, ArrayList<Artist> artists, ArrayList<Album> albums) {
        this.list = list;
        this.artists = artists;
        this.albums = albums;
        this.artist = new Artist();
        initComponents();
        ImageIcon frameIcon= new ImageIcon(getClass().getResource("/Icons/frameIcon.png"));
        setIconImage(frameIcon.getImage());

        artist = artists.get(index);
        if (artist.getImagePath()==null) {
            image.setIcon(new ImageIcon(getClass().getResource("/Icons/artistIcon.png")));
        } else {
            image.setIcon(new ImageIcon(artist.getImagePath()));
        }
        nameText.setText(artist.getName());
        yearText.setText(String.valueOf(artist.getYearOfBirth()));
        if (artist.getGender().equals("Male")) {
            maleButton.setSelected(true);
        } else {
            femaleButton.setSelected(true);
        }
        nationalityBox.setSelectedItem(artist.getNationality());
        agencyText.setText(artist.getAgency());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        genderButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        songLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        year = new javax.swing.JLabel();
        yearText = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        uploadImageButton = new javax.swing.JButton();
        functions = new javax.swing.JPanel();
        saveSongButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        albumLabel = new javax.swing.JLabel();
        agencyText = new javax.swing.JTextField();
        nationalityBox = new javax.swing.JComboBox<>();
        manufacturerLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();

        setTitle("Edit Artist");

        jPanel2.setLayout(new java.awt.GridBagLayout());

        songLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        songLabel.setForeground(new java.awt.Color(56, 132, 209));
        songLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        songLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 0);
        jPanel2.add(songLabel, gridBagConstraints);

        nameText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(nameText, gridBagConstraints);

        year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(56, 132, 209));
        year.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        year.setText("Year of birth:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel2.add(year, gridBagConstraints);

        yearText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        yearText.setPreferredSize(new java.awt.Dimension(75, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(yearText, gridBagConstraints);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/artistIcon.png"))); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        image.setIconTextGap(1);
        image.setMaximumSize(new java.awt.Dimension(125, 125));
        image.setMinimumSize(new java.awt.Dimension(125, 125));
        image.setName(""); // NOI18N
        image.setPreferredSize(new java.awt.Dimension(125, 125));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 15, 10);
        jPanel2.add(image, gridBagConstraints);

        uploadImageButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uploadImageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/upload image.png"))); // NOI18N
        uploadImageButton.setText("Upload Image");
        uploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        jPanel2.add(uploadImageButton, gridBagConstraints);

        functions.setMinimumSize(new java.awt.Dimension(100, 100));
        functions.setPreferredSize(new java.awt.Dimension(100, 50));
        functions.setLayout(new java.awt.GridBagLayout());

        saveSongButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveSongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        saveSongButton.setText("Save");
        saveSongButton.setMaximumSize(new java.awt.Dimension(88, 36));
        saveSongButton.setMinimumSize(new java.awt.Dimension(88, 36));
        saveSongButton.setPreferredSize(new java.awt.Dimension(88, 22));
        saveSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSongButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        functions.add(saveSongButton, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross mark.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(98, 36));
        cancelButton.setMinimumSize(new java.awt.Dimension(98, 36));
        cancelButton.setPreferredSize(new java.awt.Dimension(98, 22));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        functions.add(cancelButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 17, 0);
        jPanel2.add(functions, gridBagConstraints);

        albumLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        albumLabel.setForeground(new java.awt.Color(56, 132, 209));
        albumLabel.setText("Nationality:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 0);
        jPanel2.add(albumLabel, gridBagConstraints);

        agencyText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(agencyText, gridBagConstraints);

        nationalityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Australia", "Belgium", "Canada", "Denmark", "Egypt", "France", "Germany", "Greece", "Hungary", "Indonesia", "Italy", "Japan", "South Korea", "Lebanon", "Malaysia", "Netherlands", "Russia", "Sweden", "United Kingdom", "United States", "Viet Nam" }));
        nationalityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(nationalityBox, gridBagConstraints);

        manufacturerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manufacturerLabel.setForeground(new java.awt.Color(56, 132, 209));
        manufacturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        manufacturerLabel.setText("Management Agency:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        jPanel2.add(manufacturerLabel, gridBagConstraints);

        genderButtonGroup.add(maleButton);
        maleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleButton.setSelected(true);
        maleButton.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(maleButton, gridBagConstraints);

        genderButtonGroup.add(femaleButton);
        femaleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleButton.setText("Female");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(femaleButton, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageButtonActionPerformed
        String filePath = "";
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int selectedFile = chooser.showOpenDialog(this);
        if (selectedFile == JFileChooser.APPROVE_OPTION) {
            filePath = chooser.getSelectedFile().getAbsolutePath();
        }
        ImageIcon icon = new ImageIcon(filePath);
        image.setIcon(icon);
        artist.setImagePath(filePath);
        saveFile(artists);
    }//GEN-LAST:event_uploadImageButtonActionPerformed

    private void saveSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSongButtonActionPerformed
        editArtist();
        
    }//GEN-LAST:event_saveSongButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nationalityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityBoxActionPerformed
    private void editArtist() {
        ImageIcon aceptIcon = new ImageIcon(getClass().getResource("/Icons/accept mark.png"));
        ImageIcon exclamationIcon = new ImageIcon(getClass().getResource("/Icons/exclamation mark.png"));
        if (nameText.getText().isEmpty()) {
            setBorderColor(nameText, Color.red);
            JOptionPane.showMessageDialog(this, "Please enter Name of the artist", "Message", 1, exclamationIcon);
            nameText.requestFocus();
        } else if (agencyText.getText().isEmpty()) {
            setBorderColor(agencyText, Color.red);
            JOptionPane.showMessageDialog(this, "Please enter Management Agency of the artist", "Message", 1, exclamationIcon);
            agencyText.requestFocus();
        } else if (yearText.getText().isEmpty()) {
            setBorderColor(yearText, Color.red);
            JOptionPane.showMessageDialog(this, "Please enter Year of birth of the artist", "Message", 1, exclamationIcon);
            yearText.requestFocus();
        } else if (!isNumber(yearText.getText())) {
            setBorderColor(yearText, Color.red);
            JOptionPane.showMessageDialog(this, "Invalid number: " + yearText.getText(), "Message", 1, exclamationIcon);
            yearText.requestFocus();
        } else {
            artist.setName(nameText.getText());
            artist.setYearOfBirth(Integer.parseInt(yearText.getText()));
            if (maleButton.isSelected()) {
                artist.setGender("Male");
            } else {
                artist.setGender("Female");
            }
            artist.setNationality(nationalityBox.getSelectedItem().toString());
            artist.setAgency(agencyText.getText());

            saveFile(artists);
            JOptionPane.showMessageDialog(this, "Successfully edited information!", "Message", JOptionPane.INFORMATION_MESSAGE, aceptIcon);
dispose();
        }
    }

    private boolean isNumber(String a) {
        try {
            Integer.parseInt(a);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void setBorderColor(JTextField text, Color color) {
        Border bor = BorderFactory.createLineBorder(color);
        text.setBorder(bor);
    }

    private void saveFile(ArrayList<Artist> artList) {
        String fileName = "ArtistList.data";
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileName))) {
            oos.writeObject(artList);
            oos.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, new ImageIcon(getClass().getResource("/Icons/cross mark.png")));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, new ImageIcon(getClass().getResource("/Icons/cross mark.png")));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agencyText;
    private javax.swing.JLabel albumLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JPanel functions;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JComboBox<String> nationalityBox;
    private javax.swing.JButton saveSongButton;
    private javax.swing.JLabel songLabel;
    private javax.swing.JButton uploadImageButton;
    private javax.swing.JLabel year;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
