/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.songmanagement;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author LAPTOPVTC.VN
 */
public class NewMain extends javax.swing.JFrame {

    private ArrayList<Artist> artists;
    private ArrayList<Song> list;
    private ArrayList<Album> albums;

    public NewMain() {
        list = new ArrayList<>();
        artists = new ArrayList<>();
        albums = new ArrayList<>();

        loadFile();
        loadArtistFile();
        loadAlbumFile();

        initComponents();
        setLocationRelativeTo(null);
        addRowSorter(table1);
        addRowSorter(tableAlbum);
        addRowSorter(tableArtist);
        fillArtistTable(artists);
        tabSong.setVisible(true);
        if (list != null) {
            fillTable(list);
        }

        tabAlbum.setVisible(false);
        tabArtist.setVisible(false);
        tab4.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        libraryButton = new javax.swing.JButton();
        albumButton = new javax.swing.JButton();
        artistButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        tabSong = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        SearchButton1 = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        SearchType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        functions = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        tabAlbum = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAlbum = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        SearchButton2 = new javax.swing.JButton();
        searchText1 = new javax.swing.JTextField();
        SearchType1 = new javax.swing.JComboBox<>();
        functions1 = new javax.swing.JPanel();
        newAlbumButton = new javax.swing.JButton();
        editAlbum = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        addSongButton = new javax.swing.JButton();
        tabArtist = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        SearchButton3 = new javax.swing.JButton();
        searchText2 = new javax.swing.JTextField();
        SearchType2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableArtist = new javax.swing.JTable();
        functions2 = new javax.swing.JPanel();
        addArtist = new javax.swing.JButton();
        editArtist = new javax.swing.JButton();
        deleteButton2 = new javax.swing.JButton();
        tab4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        SearchButton4 = new javax.swing.JButton();
        searchText3 = new javax.swing.JTextField();
        SearchType3 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        functions3 = new javax.swing.JPanel();
        addButton3 = new javax.swing.JButton();
        editButton3 = new javax.swing.JButton();
        deleteButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setPreferredSize(new java.awt.Dimension(508, 60));
        titlePanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 132, 209));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/app Icon.png"))); // NOI18N
        jLabel1.setText("SONG MANAGEMENT");
        jLabel1.setPreferredSize(new java.awt.Dimension(311, 60));
        titlePanel.add(jLabel1);

        getContentPane().add(titlePanel, java.awt.BorderLayout.PAGE_START);

        menuPanel.setBackground(new java.awt.Color(204, 204, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(125, 369));
        menuPanel.setLayout(new java.awt.GridBagLayout());

        libraryButton.setBackground(new java.awt.Color(204, 204, 255));
        libraryButton.setText("Library");
        libraryButton.setMaximumSize(new java.awt.Dimension(125, 50));
        libraryButton.setMinimumSize(new java.awt.Dimension(125, 50));
        libraryButton.setPreferredSize(new java.awt.Dimension(125, 50));
        libraryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libraryButtonMouseClicked(evt);
            }
        });
        libraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuPanel.add(libraryButton, gridBagConstraints);

        albumButton.setBackground(new java.awt.Color(204, 204, 255));
        albumButton.setText("Albums");
        albumButton.setMaximumSize(new java.awt.Dimension(125, 50));
        albumButton.setMinimumSize(new java.awt.Dimension(125, 50));
        albumButton.setPreferredSize(new java.awt.Dimension(125, 50));
        albumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuPanel.add(albumButton, gridBagConstraints);

        artistButton.setBackground(new java.awt.Color(204, 204, 255));
        artistButton.setText("Artist");
        artistButton.setMaximumSize(new java.awt.Dimension(125, 50));
        artistButton.setMinimumSize(new java.awt.Dimension(125, 50));
        artistButton.setPreferredSize(new java.awt.Dimension(125, 50));
        artistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuPanel.add(artistButton, gridBagConstraints);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("jButton4");
        jButton4.setMaximumSize(new java.awt.Dimension(125, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(125, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(125, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuPanel.add(jButton4, gridBagConstraints);

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton5.setText("HOME");
        jButton5.setMaximumSize(new java.awt.Dimension(125, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(125, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(125, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuPanel.add(jButton5, gridBagConstraints);

        getContentPane().add(menuPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setLayout(new javax.swing.OverlayLayout(contentPanel));

        tabSong.setBackground(new java.awt.Color(255, 255, 255));
        tabSong.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabSong.setMinimumSize(new java.awt.Dimension(822, 416));
        tabSong.setPreferredSize(new java.awt.Dimension(822, 416));
        tabSong.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        SearchButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton1.setForeground(java.awt.Color.lightGray);
        SearchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        SearchButton1.setText("Search");
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel7.add(SearchButton1, gridBagConstraints);

        searchText.setMinimumSize(new java.awt.Dimension(150, 22));
        searchText.setPreferredSize(new java.awt.Dimension(200, 22));
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 5, 0);
        jPanel7.add(searchText, gridBagConstraints);

        SearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Song", "Author ", "Singer", "Manufacturer", "Years of Release", "Genre", "Album", " " }));
        SearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 6, 0);
        jPanel7.add(SearchType, gridBagConstraints);

        tabSong.add(jPanel7, java.awt.BorderLayout.NORTH);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Song", "Artist", "Genre", "Album", "Release Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.setName(""); // NOI18N
        table1.setRequestFocusEnabled(false);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);
        table1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tabSong.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        functions.setMinimumSize(new java.awt.Dimension(100, 100));
        functions.setPreferredSize(new java.awt.Dimension(100, 40));
        functions.setLayout(new java.awt.GridBagLayout());

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setMaximumSize(new java.awt.Dimension(180, 136));
        addButton.setMinimumSize(new java.awt.Dimension(80, 36));
        addButton.setOpaque(true);
        addButton.setPreferredSize(new java.awt.Dimension(80, 22));
        addButton.setRequestFocusEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 7);
        functions.add(addButton, gridBagConstraints);

        editButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editButton.setText("Edit");
        editButton.setMaximumSize(new java.awt.Dimension(84, 36));
        editButton.setMinimumSize(new java.awt.Dimension(84, 36));
        editButton.setPreferredSize(new java.awt.Dimension(84, 22));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        functions.add(editButton, gridBagConstraints);

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setMaximumSize(new java.awt.Dimension(98, 36));
        deleteButton.setMinimumSize(new java.awt.Dimension(98, 36));
        deleteButton.setPreferredSize(new java.awt.Dimension(98, 22));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        functions.add(deleteButton, gridBagConstraints);

        playButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/play.png"))); // NOI18N
        playButton.setText("Play");
        playButton.setMaximumSize(new java.awt.Dimension(84, 36));
        playButton.setMinimumSize(new java.awt.Dimension(84, 36));
        playButton.setPreferredSize(new java.awt.Dimension(84, 22));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        functions.add(playButton, gridBagConstraints);

        tabSong.add(functions, java.awt.BorderLayout.SOUTH);

        contentPanel.add(tabSong);

        tabAlbum.setBackground(new java.awt.Color(255, 255, 255));
        tabAlbum.setName(""); // NOI18N
        tabAlbum.setPreferredSize(new java.awt.Dimension(822, 394));
        tabAlbum.setLayout(new java.awt.BorderLayout());

        tableAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Album", "Artist", "Genre", "Release Year", "Songs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAlbum.setName(""); // NOI18N
        tableAlbum.getTableHeader().setReorderingAllowed(false);
        tableAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlbumMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableAlbum);

        tabAlbum.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        SearchButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton2.setForeground(java.awt.Color.lightGray);
        SearchButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        SearchButton2.setText("Search");
        SearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel8.add(SearchButton2, gridBagConstraints);

        searchText1.setMinimumSize(new java.awt.Dimension(150, 22));
        searchText1.setPreferredSize(new java.awt.Dimension(200, 22));
        searchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 5, 0);
        jPanel8.add(searchText1, gridBagConstraints);

        SearchType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Song", "Author ", "Singer", "Manufacturer", "Years of Release", "Genre", "Album", " " }));
        SearchType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchType1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 6, 0);
        jPanel8.add(SearchType1, gridBagConstraints);

        tabAlbum.add(jPanel8, java.awt.BorderLayout.NORTH);

        functions1.setMinimumSize(new java.awt.Dimension(100, 100));
        functions1.setPreferredSize(new java.awt.Dimension(100, 40));
        functions1.setLayout(new java.awt.GridBagLayout());

        newAlbumButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newAlbumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addAlbum.png"))); // NOI18N
        newAlbumButton.setText("Create New Album");
        newAlbumButton.setMaximumSize(new java.awt.Dimension(180, 136));
        newAlbumButton.setMinimumSize(new java.awt.Dimension(80, 36));
        newAlbumButton.setOpaque(true);
        newAlbumButton.setPreferredSize(new java.awt.Dimension(180, 22));
        newAlbumButton.setRequestFocusEnabled(false);
        newAlbumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAlbumButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 7);
        functions1.add(newAlbumButton, gridBagConstraints);

        editAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editAlbum.setText("Edit");
        editAlbum.setMaximumSize(new java.awt.Dimension(84, 36));
        editAlbum.setMinimumSize(new java.awt.Dimension(84, 36));
        editAlbum.setPreferredSize(new java.awt.Dimension(84, 22));
        editAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAlbumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        functions1.add(editAlbum, gridBagConstraints);

        deleteButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        deleteButton1.setText("Delete");
        deleteButton1.setMaximumSize(new java.awt.Dimension(98, 36));
        deleteButton1.setMinimumSize(new java.awt.Dimension(98, 36));
        deleteButton1.setPreferredSize(new java.awt.Dimension(98, 22));
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        functions1.add(deleteButton1, gridBagConstraints);

        addSongButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addSongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addsong.png"))); // NOI18N
        addSongButton.setText("Add Song");
        addSongButton.setMaximumSize(new java.awt.Dimension(84, 36));
        addSongButton.setMinimumSize(new java.awt.Dimension(84, 36));
        addSongButton.setPreferredSize(new java.awt.Dimension(150, 22));
        addSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        functions1.add(addSongButton, gridBagConstraints);

        tabAlbum.add(functions1, java.awt.BorderLayout.SOUTH);

        contentPanel.add(tabAlbum);

        tabArtist.setBackground(new java.awt.Color(255, 255, 255));
        tabArtist.setMinimumSize(new java.awt.Dimension(822, 416));
        tabArtist.setPreferredSize(new java.awt.Dimension(822, 416));
        tabArtist.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        SearchButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton3.setForeground(java.awt.Color.lightGray);
        SearchButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        SearchButton3.setText("Search");
        SearchButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel9.add(SearchButton3, gridBagConstraints);

        searchText2.setMinimumSize(new java.awt.Dimension(150, 22));
        searchText2.setPreferredSize(new java.awt.Dimension(200, 22));
        searchText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 5, 0);
        jPanel9.add(searchText2, gridBagConstraints);

        SearchType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Song", "Author ", "Singer", "Manufacturer", "Years of Release", "Genre", "Album", " " }));
        SearchType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchType2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 6, 0);
        jPanel9.add(SearchType2, gridBagConstraints);

        tabArtist.add(jPanel9, java.awt.BorderLayout.NORTH);

        tableArtist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Artist", "Year of Birth", "Gender", "Nationality", "Management Agency", "Albums"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableArtist.setColumnSelectionAllowed(false);
        tableArtist.setName(""); // NOI18N
        tableArtist.getTableHeader().setReorderingAllowed(false);
        tableArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableArtistMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableArtist);

        tabArtist.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        functions2.setMinimumSize(new java.awt.Dimension(100, 100));
        functions2.setPreferredSize(new java.awt.Dimension(100, 40));
        functions2.setLayout(new java.awt.GridBagLayout());

        addArtist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addSinger.png"))); // NOI18N
        addArtist.setText("New Artist\n");
        addArtist.setMaximumSize(new java.awt.Dimension(180, 136));
        addArtist.setMinimumSize(new java.awt.Dimension(100, 36));
        addArtist.setOpaque(true);
        addArtist.setPreferredSize(new java.awt.Dimension(150, 22));
        addArtist.setRequestFocusEnabled(false);
        addArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArtistActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 7);
        functions2.add(addArtist, gridBagConstraints);

        editArtist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editArtist.setText("Edit");
        editArtist.setMaximumSize(new java.awt.Dimension(84, 36));
        editArtist.setMinimumSize(new java.awt.Dimension(84, 36));
        editArtist.setPreferredSize(new java.awt.Dimension(84, 22));
        editArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editArtistActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        functions2.add(editArtist, gridBagConstraints);

        deleteButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        deleteButton2.setText("Delete");
        deleteButton2.setMaximumSize(new java.awt.Dimension(98, 36));
        deleteButton2.setMinimumSize(new java.awt.Dimension(98, 36));
        deleteButton2.setPreferredSize(new java.awt.Dimension(98, 22));
        deleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        functions2.add(deleteButton2, gridBagConstraints);

        tabArtist.add(functions2, java.awt.BorderLayout.SOUTH);

        contentPanel.add(tabArtist);

        tab4.setBackground(new java.awt.Color(255, 255, 255));
        tab4.setMinimumSize(new java.awt.Dimension(822, 416));
        tab4.setPreferredSize(new java.awt.Dimension(822, 416));
        tab4.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        SearchButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton4.setForeground(java.awt.Color.lightGray);
        SearchButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        SearchButton4.setText("Search");
        SearchButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel10.add(SearchButton4, gridBagConstraints);

        searchText3.setMinimumSize(new java.awt.Dimension(150, 22));
        searchText3.setPreferredSize(new java.awt.Dimension(200, 22));
        searchText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 5, 0);
        jPanel10.add(searchText3, gridBagConstraints);

        SearchType3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Song", "Author ", "Singer", "Manufacturer", "Years of Release", "Genre", "Album", " " }));
        SearchType3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchType3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 6, 0);
        jPanel10.add(SearchType3, gridBagConstraints);

        tab4.add(jPanel10, java.awt.BorderLayout.NORTH);

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Song", "Artist", "Genre", "Album", "Release Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table4.setName(""); // NOI18N
        table4.getTableHeader().setReorderingAllowed(false);
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table4);

        tab4.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        functions3.setMinimumSize(new java.awt.Dimension(100, 100));
        functions3.setPreferredSize(new java.awt.Dimension(100, 40));
        functions3.setLayout(new java.awt.GridBagLayout());

        addButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        addButton3.setText("Add");
        addButton3.setMaximumSize(new java.awt.Dimension(180, 136));
        addButton3.setMinimumSize(new java.awt.Dimension(80, 36));
        addButton3.setOpaque(true);
        addButton3.setPreferredSize(new java.awt.Dimension(80, 22));
        addButton3.setRequestFocusEnabled(false);
        addButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 7);
        functions3.add(addButton3, gridBagConstraints);

        editButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editButton3.setText("Edit");
        editButton3.setMaximumSize(new java.awt.Dimension(84, 36));
        editButton3.setMinimumSize(new java.awt.Dimension(84, 36));
        editButton3.setPreferredSize(new java.awt.Dimension(84, 22));
        editButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        functions3.add(editButton3, gridBagConstraints);

        deleteButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        deleteButton3.setText("Delete");
        deleteButton3.setMaximumSize(new java.awt.Dimension(98, 36));
        deleteButton3.setMinimumSize(new java.awt.Dimension(98, 36));
        deleteButton3.setPreferredSize(new java.awt.Dimension(98, 22));
        deleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        functions3.add(deleteButton3, gridBagConstraints);

        tab4.add(functions3, java.awt.BorderLayout.SOUTH);

        contentPanel.add(tab4);

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistButtonActionPerformed
        tabSong.setVisible(false);
        tabAlbum.setVisible(false);
        tabArtist.setVisible(true);
        tab4.setVisible(false);
    }//GEN-LAST:event_artistButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void libraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryButtonActionPerformed

    }//GEN-LAST:event_libraryButtonActionPerformed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        //  search();
    }//GEN-LAST:event_SearchButton1ActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void SearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTypeActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddNewSong addnewsong = new AddNewSong(list, artists, albums);
        addnewsong.setVisible(true);
        addnewsong.setLocationRelativeTo(this);
        if (!addnewsong.isVisible()) {
            fillTable(list);
        }
        fillTable(list);
        saveFile();
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (table1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a song to edit", "Message", 1, exclamationIcon);
        } else {
            EditSongFrame edit = new EditSongFrame(list, table1.getSelectedRow(), artists, albums);
            edit.setLocationRelativeTo(this);
            edit.setVisible(true);
            if (!edit.isVisible()) {
                fillTable(list);
            }
        }
        fillTable(list);
        saveFile();
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (table1.getSelectedRow() != -1) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete the song: " + list.get(table1.getSelectedRow()).getNameSong(), "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, questionIcon);
            if (option == JOptionPane.YES_OPTION) {
                list.remove(table1.getSelectedRow());

            }
        }
        fillTable(list);
        saveFile();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void libraryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryButtonMouseClicked
        tabSong.setVisible(true);
        fillTable(list);
        tabAlbum.setVisible(false);
        tabArtist.setVisible(false);
        tab4.setVisible(false);
    }//GEN-LAST:event_libraryButtonMouseClicked

    private void albumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumButtonActionPerformed
        tabSong.setVisible(false);
        tabAlbum.setVisible(true);
        tabArtist.setVisible(false);
        tab4.setVisible(false);
    }//GEN-LAST:event_albumButtonActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked


    }//GEN-LAST:event_table1MouseClicked

    private void SearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButton2ActionPerformed

    private void searchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1ActionPerformed

    private void SearchType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchType1ActionPerformed

    private void tableAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlbumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAlbumMouseClicked

    private void newAlbumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAlbumButtonActionPerformed
        AddNewAlbum addnewalbum = new AddNewAlbum(list, artists, albums);
        addnewalbum.setVisible(true);
        addnewalbum.setLocationRelativeTo(this);
        fillAlbumTable(albums);
        saveAlbumFile();
    }//GEN-LAST:event_newAlbumButtonActionPerformed

    private void editAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAlbumActionPerformed
        if (tableAlbum.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select an artist to edit", "Message", 1, exclamationIcon);
        } else {
            EditAlbumFrame edit = new EditAlbumFrame(list, tableAlbum.getSelectedRow(), artists, albums);
            edit.setLocationRelativeTo(this);
            edit.setVisible(true);
            fillAlbumTable(albums);
            saveAlbumFile();
        }
    }//GEN-LAST:event_editAlbumActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        if (tableAlbum.getSelectedRow() != -1) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete the album: " + albums.get(tableAlbum.getSelectedRow()).getAlbumName(), "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, questionIcon);
            if (option == JOptionPane.YES_OPTION) {
                albums.remove(tableAlbum.getSelectedRow());
            }
        }
        fillAlbumTable(albums);
        saveAlbumFile();
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void SearchButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButton3ActionPerformed

    private void searchText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText2ActionPerformed

    private void SearchType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchType2ActionPerformed

    private void tableArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableArtistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableArtistMouseClicked

    private void addArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArtistActionPerformed
        AddNewArtist addnewartist = new AddNewArtist(list, artists, albums);
        addnewartist.setVisible(true);
        addnewartist.setLocationRelativeTo(this);

        fillArtistTable(artists);
        saveFile(artists);

    }//GEN-LAST:event_addArtistActionPerformed

    private void editArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editArtistActionPerformed
        if (tableArtist.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select an artist to edit", "Message", 1, exclamationIcon);
        } else {
            EditArtistFrame edit = new EditArtistFrame(list, tableArtist.getSelectedRow(), artists, albums);
            edit.setLocationRelativeTo(this);
            edit.setVisible(true);
            fillArtistTable(artists);
            saveFile(artists);

        }
    }//GEN-LAST:event_editArtistActionPerformed

    private void deleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton2ActionPerformed
        if (tableArtist.getSelectedRow() != -1) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete the artist: " + artists.get(tableArtist.getSelectedRow()).getName(), "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, questionIcon);
            if (option == JOptionPane.YES_OPTION) {
                artists.remove(tableArtist.getSelectedRow());

            }
        }
        fillArtistTable(artists);
        saveFile(artists);
    }//GEN-LAST:event_deleteButton2ActionPerformed

    private void SearchButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButton4ActionPerformed

    private void searchText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText3ActionPerformed

    private void SearchType3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchType3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchType3ActionPerformed

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table4MouseClicked

    private void addButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton3ActionPerformed

    private void editButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButton3ActionPerformed

    private void deleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton3ActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        if (table1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a song to play", "Message", 1, exclamationIcon);
        } else {
            Song song = list.get(table1.getSelectedRow());
            musicPlayerForm player = new musicPlayerForm(song);
            player.setVisible(true);
            player.setLocationRelativeTo(this);

        }

    }//GEN-LAST:event_playButtonActionPerformed

    private void addSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongButtonActionPerformed
         if (tableAlbum.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select an album to add songs", "Message", 1, exclamationIcon);
        } else {
            EditAlbumFrame edit = new EditAlbumFrame(list, tableAlbum.getSelectedRow(), artists, albums);
            edit.setLocationRelativeTo(this);
            edit.setVisible(true);
            fillAlbumTable(albums);
            saveAlbumFile();
        }
    }//GEN-LAST:event_addSongButtonActionPerformed
    private void addRowSorter(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table.setRowSorter(sorter);
    }

    private void fillTable(ArrayList<Song> list) {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        int rowCount = table1.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Song song : list) {
            Object[] row = new Object[]{song.getNameSong(), song.getArtist(), song.getGenre(), song.getAlbum(), song.getYear()};
            model.addRow(row);
        }
    }

    private void fillArtistTable(ArrayList<Artist> artists) {
        DefaultTableModel model = (DefaultTableModel) tableArtist.getModel();
        int rowCount = tableArtist.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Artist artist : artists) {
            Object[] row = new Object[]{artist.getName(), artist.getYearOfBirth(), artist.getGender(), artist.getNationality(), artist.getAgency(), artist.getAlbumsSize()};
            model.addRow(row);
        }
    }

    private void fillAlbumTable(ArrayList<Album> albums) {
        DefaultTableModel model = (DefaultTableModel) tableAlbum.getModel();
        int rowCount = tableAlbum.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Album album : albums) {
            Object[] row = new Object[]{album.getAlbumName(), album.getArtist(), album.getGenre(), album.getYearOfRelease(), album.getSongsSize()};
            model.addRow(row);
        }
    }

    private ImageIcon crossIcon = new ImageIcon(getClass().getResource("/Icons/cross mark.png"));
    private ImageIcon aceptIcon = new ImageIcon(getClass().getResource("/Icons/accept mark.png"));
    private ImageIcon exclamationIcon = new ImageIcon(getClass().getResource("/Icons/exclamation mark.png"));
    private ImageIcon questionIcon = new ImageIcon(getClass().getResource("/Icons/question mark.png"));

    private void loadFile() {
        String fileName = "SongList.data";
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileName))) {
            this.list = (ArrayList<Song>) ois.readObject();
            ois.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1, crossIcon);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1, crossIcon);
        }
    }

    private void loadArtistFile() {
        String fileName = "ArtistList.data";
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileName))) {
            this.artists = (ArrayList<Artist>) ois.readObject();
            ois.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1, crossIcon);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1, crossIcon);
        }
    }

    private void loadAlbumFile() {
        String fileName = "AlbumList.data";
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileName))) {
            this.albums = (ArrayList<Album>) ois.readObject();
            ois.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1, crossIcon);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1, crossIcon);
        }
    }

    private void saveFile() {
        String fileName = "SongList.data";
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileName))) {
            oos.writeObject(list);
            oos.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, crossIcon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, crossIcon);
        }
    }

    private void saveFile(ArrayList<Artist> artList) {
        String fileName = "ArtistList.data";
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileName))) {
            oos.writeObject(artList);
            oos.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, new ImageIcon(getClass().getResource("/Icons/cross mark.png")));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, new ImageIcon(getClass().getResource("/Icons/cross mark.png")));
        }
    }

    private void saveAlbumFile() {
        String fileName = "AlbumList.data";
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileName))) {
            oos.writeObject(albums);
            oos.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, new ImageIcon(getClass().getResource("/Icons/cross mark.png")));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1, new ImageIcon(getClass().getResource("/Icons/cross mark.png")));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton1;
    private javax.swing.JButton SearchButton2;
    private javax.swing.JButton SearchButton3;
    private javax.swing.JButton SearchButton4;
    private javax.swing.JComboBox<String> SearchType;
    private javax.swing.JComboBox<String> SearchType1;
    private javax.swing.JComboBox<String> SearchType2;
    private javax.swing.JComboBox<String> SearchType3;
    private javax.swing.JButton addArtist;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton3;
    private javax.swing.JButton addSongButton;
    private javax.swing.JButton albumButton;
    private javax.swing.JButton artistButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JButton deleteButton3;
    private javax.swing.JButton editAlbum;
    private javax.swing.JButton editArtist;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editButton3;
    private javax.swing.JPanel functions;
    private javax.swing.JPanel functions1;
    private javax.swing.JPanel functions2;
    private javax.swing.JPanel functions3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton libraryButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton newAlbumButton;
    private javax.swing.JButton playButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField searchText1;
    private javax.swing.JTextField searchText2;
    private javax.swing.JTextField searchText3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tabAlbum;
    private javax.swing.JPanel tabArtist;
    private javax.swing.JPanel tabSong;
    private javax.swing.JTable table1;
    private javax.swing.JTable table4;
    private javax.swing.JTable tableAlbum;
    private javax.swing.JTable tableArtist;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
